Sprint 11
4eKeP/ImageFeedYandexPracticum pull request #5
Opened 2023-10-20 18:20 UTC by 4eKeP

2023-10-21 12:24 UTC, protos17 requested changes

2023-10-21 12:24 UTC, protos17 commented on ImageFeedYandexPracticum/SplashView/SplashViewController.swift
>                  self.switchToTabBarViewController()
Данный switchToTabBarViewController() необходимо убрать, потому что переход должен осуществляться после получения аватарки и он у тебя правильно вызывается в fetchProfile

2023-10-21 12:24 UTC, protos17 commented on ImageFeedYandexPracticum/Halper/UIBlockingProgressHUD.swift
> +import Foundation
При импорте UIKit можно не импортировать Foundation, потому что первый содержит в себе второй

2023-10-21 12:24 UTC, protos17 commented on ImageFeedYandexPracticum/ProfileImageService/ProfileImageService.swift
> +                                          baseURL: URL(string: "https://api.unsplash.com")!,
Рекомендую перенести в Constants

2023-10-21 12:24 UTC, protos17 commented on ImageFeedYandexPracticum/ProfileImageService/ProfileImageService.swift
> +    static let DidChangeNotification = Notification.Name(rawValue: "ProfileImageProviderDidChange")
Константы принято писать с маленькой буквы

2023-10-21 12:24 UTC, protos17 commented on ImageFeedYandexPracticum/ProfileService/Profile.swift
> +        self.bio = body.bio ?? "Тут пока что пусто"
В качестве значения по умолчанию рекомендую указать пустую строку

2023-10-21 12:24 UTC, protos17 commented on ImageFeedYandexPracticum/ProfileService/ProfileService.swift
> +                                          baseURL: URL(string: "https://api.unsplash.com")!,
Рекомендую перенести в Constants

2023-10-21 12:24 UTC, protos17 commented on ImageFeedYandexPracticum/SplashView/SplashViewController.swift
> +                UIBlockingProgressHUD.dismiss()
Рекомендую избавиться от дублирования UIBlockingProgressHUD.dismiss() путем выноса в общую область видимости

2023-10-21 12:24 UTC, protos17 commented on ImageFeedYandexPracticum/SplashView/SplashViewController.swift
> +                UIBlockingProgressHUD.dismiss()
Здесь тоже рекомендую убрать дублирование UIBlockingProgressHUD.dismiss()

2023-10-21 12:24 UTC, protos17 commented on ImageFeedYandexPracticum/SplashView/SplashViewController.swift
> +            }
Если в обоих кейсах выполняется одно и то же, то нет смысла писать switch, лучше просто сразу написать UIBlockingProgressHUD.dismiss()

2023-10-21 12:24 UTC, protos17 commented on ImageFeedYandexPracticum/ProfileImageService/ProfileImageService.swift
> +        let task = urlSession.objectTask(for: request) { (result: Result<UserResult, Error>) in
Сильная ссылка, необходимо добавить [weak self]

2023-10-21 14:23 UTC, 4eKeP commented on ImageFeedYandexPracticum/ProfileImageService/ProfileImageService.swift
> +                                          baseURL: URL(string: "https://api.unsplash.com")!,
спасибо что напомнили, я и забыл что добавлял их

2023-10-21 14:24 UTC, 4eKeP commented on ImageFeedYandexPracticum/SplashView/SplashViewController.swift
>                  self.switchToTabBarViewController()
спасибо большое, забыл удалить

2023-10-22 11:15 UTC, protos17 approved these changes

2023-10-22 11:15 UTC, protos17 commented on ImageFeedYandexPracticum/ProfileImageService/ProfileImageService.swift
>  }
Рекомендую улучшить, написав их в отдельном экстеншене и вызывать через точку

extension Notification.Name {
    static let didChangeNotification = Notification.Name("ProfileImageProviderDidChange")
}

2023-10-22 11:15 UTC, protos17 commented on ImageFeedYandexPracticum/SplashView/SplashViewController.swift
> +    //            UIBlockingProgressHUD.dismiss()
Лишний закомментированный код рекомендую удалять

2023-10-22 11:15 UTC, protos17 commented on ImageFeedYandexPracticum/SplashView/SplashViewController.swift
> +            guard let token = oauth2TokenStorage.token else { return }
Два раза одно и то же проверяется, лучше оставить одно:

if let token = oauth2TokenStorage.token {
...

2023-10-23 04:48 UTC, 4eKeP commented on ImageFeedYandexPracticum/SplashView/SplashViewController.swift
> +            guard let token = oauth2TokenStorage.token else { return }
понимаю просто хотел избавиться от forceunwrap

2023-10-23 12:44 UTC, merged